# Generated by Django 5.0.1 on 2025-11-12 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('IdEstado', models.AutoField(primary_key=True, serialize=False)),
                ('Estado', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado',
                'ordering': ['IdEstado'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('IdMesa', models.AutoField(primary_key=True, serialize=False)),
                ('Mesa', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'mesa',
                'ordering': ['IdMesa'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('PrimerNombre', models.CharField(max_length=50)),
                ('SegundoNombre', models.CharField(blank=True, max_length=50, null=True)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'persona',
                'ordering': ['idPersona'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('IdTipoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('TipoProducto', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_producto',
                'ordering': ['IdTipoProducto'],
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('IdTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('TipoUsuario', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'ordering': ['IdTipoUsuario'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('IdProducto', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=100)),
                ('Valor', models.FloatField()),
                ('IdEstado', models.ForeignKey(db_column='IdEstado', on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
                ('IdTipoProducto', models.ForeignKey(db_column='IdTipoProducto', on_delete=django.db.models.deletion.CASCADE, to='api.tipoproducto')),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['IdProducto'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('IdEstado', models.ForeignKey(db_column='IdEstado', on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
                ('IdPersona', models.ForeignKey(db_column='IdPersona', on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('IdTipoUsuario', models.ForeignKey(db_column='IdTipoUsuario', on_delete=django.db.models.deletion.CASCADE, to='api.tipousuario')),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['IdUsuario'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('IdOrden', models.AutoField(primary_key=True, serialize=False)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('IdEstado', models.ForeignKey(db_column='IdEstado', on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
                ('IdMesa', models.ForeignKey(db_column='IdMesa', on_delete=django.db.models.deletion.CASCADE, to='api.mesa')),
                ('IdUsuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'orden',
                'ordering': ['-FechaCreacion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=1)),
                ('Notas', models.TextField(blank=True, null=True)),
                ('IdOrden', models.ForeignKey(db_column='IdOrden', on_delete=django.db.models.deletion.CASCADE, related_name='productos_orden', to='api.orden')),
                ('IdProducto', models.ForeignKey(db_column='IdProducto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'producto_orden',
                'unique_together': {('IdProducto', 'IdOrden')},
            },
        ),
    ]
