# Generated by Django 5.0.1

from django.db import migrations
import bcrypt


def create_initial_data(apps, schema_editor):
    # Obtener los modelos
    Estado = apps.get_model('api', 'Estado')
    TipoProducto = apps.get_model('api', 'TipoProducto')
    TipoUsuario = apps.get_model('api', 'TipoUsuario')
    Persona = apps.get_model('api', 'Persona')
    Usuario = apps.get_model('api', 'Usuario')
    Mesa = apps.get_model('api', 'Mesa')
    Producto = apps.get_model('api', 'Producto')
    Orden = apps.get_model('api', 'Orden')
    ProductoOrden = apps.get_model('api', 'ProductoOrden')

    # Crear Estados
    estados_data = [
        'Activo', 'Pendiente', 'En Preparación', 'Listo',
        'Entregado', 'Cancelado', 'Inactivo'
    ]
    estados = {}
    for estado_nombre in estados_data:
        estado, _ = Estado.objects.get_or_create(Estado=estado_nombre)
        estados[estado_nombre] = estado

    # Crear Tipos de Usuario
    tipos_usuario_data = ['Administrador', 'Mesero', 'Cocina']
    tipos_usuario = {}
    for tipo_nombre in tipos_usuario_data:
        tipo, _ = TipoUsuario.objects.get_or_create(TipoUsuario=tipo_nombre)
        tipos_usuario[tipo_nombre] = tipo

    # Crear Tipos de Producto
    tipos_producto_data = ['Entrada', 'Plato Principal', 'Bebida', 'Postre', 'Acompañamiento']
    tipos_producto = {}
    for tipo_nombre in tipos_producto_data:
        tipo, _ = TipoProducto.objects.get_or_create(TipoProducto=tipo_nombre)
        tipos_producto[tipo_nombre] = tipo

    # Crear Personas
    personas_data = [
        {'PrimerNombre': 'Juan', 'PrimerApellido': 'Pérez', 'SegundoApellido': 'García'},
        {'PrimerNombre': 'María', 'PrimerApellido': 'González', 'SegundoApellido': 'López'},
        {'PrimerNombre': 'Carlos', 'PrimerApellido': 'Martínez', 'SegundoApellido': 'Rodríguez'},
        {'PrimerNombre': 'Chef', 'PrimerApellido': 'Principal', 'SegundoApellido': ''},
    ]
    personas = []
    for persona_data in personas_data:
        persona, _ = Persona.objects.get_or_create(
            PrimerNombre=persona_data['PrimerNombre'],
            PrimerApellido=persona_data['PrimerApellido'],
            defaults={'SegundoApellido': persona_data.get('SegundoApellido', '')}
        )
        personas.append(persona)

    # Crear Usuarios de prueba
    usuarios_data = [
        {
            'IdPersona': personas[0],
            'IdTipoUsuario': tipos_usuario['Administrador'],
            'Username': 'admin',
            'Password': bcrypt.hashpw('admin123'.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'),
            'IdEstado': estados['Activo']
        },
        {
            'IdPersona': personas[1],
            'IdTipoUsuario': tipos_usuario['Mesero'],
            'Username': 'maria',
            'Password': bcrypt.hashpw('mesero123'.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'),
            'IdEstado': estados['Activo']
        },
        {
            'IdPersona': personas[2],
            'IdTipoUsuario': tipos_usuario['Mesero'],
            'Username': 'carlos',
            'Password': bcrypt.hashpw('mesero123'.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'),
            'IdEstado': estados['Activo']
        },
        {
            'IdPersona': personas[3],
            'IdTipoUsuario': tipos_usuario['Cocina'],
            'Username': 'cocina',
            'Password': bcrypt.hashpw('cocina123'.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'),
            'IdEstado': estados['Activo']
        },
    ]
    for usuario_data in usuarios_data:
        Usuario.objects.get_or_create(
            Username=usuario_data['Username'],
            defaults=usuario_data
        )

    # Crear Mesas
    for i in range(1, 11):
        Mesa.objects.get_or_create(Mesa=f'Mesa {i}')

    # Crear Productos
    productos_data = [
        {'IdTipoProducto': tipos_producto['Plato Principal'], 'NombreProducto': 'Pizza Margherita', 'Valor': 12000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Plato Principal'], 'NombreProducto': 'Pizza Pepperoni', 'Valor': 14000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Plato Principal'], 'NombreProducto': 'Hamburguesa Clásica', 'Valor': 10000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Plato Principal'], 'NombreProducto': 'Hamburguesa BBQ', 'Valor': 12000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Plato Principal'], 'NombreProducto': 'Pasta Carbonara', 'Valor': 13000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Plato Principal'], 'NombreProducto': 'Pasta Bolognesa', 'Valor': 13000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Entrada'], 'NombreProducto': 'Ensalada César', 'Valor': 8000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Entrada'], 'NombreProducto': 'Ensalada Mixta', 'Valor': 7000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Acompañamiento'], 'NombreProducto': 'Papas Fritas', 'Valor': 4000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Acompañamiento'], 'NombreProducto': 'Aros de Cebolla', 'Valor': 4500, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Entrada'], 'NombreProducto': 'Alitas de Pollo', 'Valor': 9000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Entrada'], 'NombreProducto': 'Nachos', 'Valor': 8000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Bebida'], 'NombreProducto': 'Refresco', 'Valor': 2500, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Bebida'], 'NombreProducto': 'Jugo Natural', 'Valor': 3000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Bebida'], 'NombreProducto': 'Cerveza', 'Valor': 4000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Bebida'], 'NombreProducto': 'Vino', 'Valor': 15000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Postre'], 'NombreProducto': 'Tiramisú', 'Valor': 6000, 'IdEstado': estados['Activo']},
        {'IdTipoProducto': tipos_producto['Postre'], 'NombreProducto': 'Helado', 'Valor': 5000, 'IdEstado': estados['Activo']},
    ]
    for producto_data in productos_data:
        Producto.objects.get_or_create(
            NombreProducto=producto_data['NombreProducto'],
            defaults=producto_data
        )


def reverse_initial_data(apps, schema_editor):
    # No hacemos nada al revertir, los datos se mantienen
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]
